disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Casa de JuJu"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/rev.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Another JuJu Production"
  # copyright = "Another JuJu Production"

[params.author]
   name = "JuJu DarÃ­o"
   email = "mail@juju.casa"
   image = "img/Ghiblied.jpg"
   imageQuality = 96
   headline = "NeoAboriginal ğŸ¦Š <br> Kambo practitioner ğŸ¸ <br> Amplifier of truth ğŸ’ <br> Agorism and decentralization ğŸŒ"
   bio = "Blod, kÃ¤rlek, jord, dag fÃ¶r dag, ord fÃ¶r ord<br>Inuti, utanfÃ¶r, runtomkring och in igenom<br>Allomfattande"
   links = [
     { rss = "https://juju.casa/index.xml" },
     { email = "mailto:mail@juju.casa" },
     { spotify = "https://open.spotify.com/user/jujudario" },
     { x-twitter = "https://twitter.com/jujudario" },
 ]
