[[main]]
  name = "Kategorier ğŸ—ƒï¸"
  pageRef = "#"
  weight = 10

[[main]]
  name = "Notater ğŸ“"
  parent = "Kategorier ğŸ—ƒï¸"
  pageRef = "note"
  weight = 10

[[main]]
   name = "Tagger ğŸ·ï¸"
   pageRef = "tags"
   weight = 20

[[main]]
  name = "Musikk ğŸµ"
  parent = "Kategorier ğŸ—ƒï¸"
  pageRef = "music"
  weight = 20

#[[main]]
#  name = "Sitater ğŸ—£ï¸"
#  parent = "Kategorier ğŸ—ƒï¸"
#  pageRef = "quote"
#  weight = 40

[[main]]
  name = "Bokmerker ğŸ”–"
  parent = "Kategorier ğŸ—ƒï¸"
  pageRef = "bookmark"
  weight = 40

[[main]]
  name = "Videoer ğŸ“½ï¸"
  parent = "Kategorier ğŸ—ƒï¸"
  pageRef = "video"
  weight = 50

#[[main]]
#  name = "Liker â¤ï¸"
#  parent = "Kategorier ğŸ—ƒï¸"
#  pageRef = "like"
#  weight = 70

[[main]]
  name = "Republisert ğŸ”"
  parent = "Kategorier ğŸ—ƒï¸"
  pageRef= "repost"
  weight = 60

[[main]]
  name = "Lest ğŸ“š"
  parent = "Kategorier ğŸ—ƒï¸"
  pageRef = "read"
  weight = 30

#[[main]]
#  name = "Podcaster ğŸ™ï¸"
#  parent = "Kategorier ğŸ—ƒï¸"
#  url = "https://open.spotify.com/playlist/2zVbDT1D2MJFRNU6Po2blC?si=d9a65f0280ed4a49"
#  weight = 100

#[[main]]
#  name = "Checkins ğŸ“"
#  parent = "Stream âš¡"
#  pageRef = "checkin"
#  weight = 40

[[main]]
  name = "Kambo ğŸ¸"
  url = "https://kam.bo"
  weight = 30

[[main]]
  name = "Om ğŸ§”ğŸ»â€â™‚ï¸"
  url = "/about"
  weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tagger ğŸ·ï¸"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Kategorier ğŸ—ƒï¸"
   pageRef = "category"
   weight = 20
