# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Stream âš¡"
#  pageRef = "#"
#  weight = 10

[[main]]
  name = "Categories ğŸ—ƒï¸"
  pageRef = "#"
  weight = 10

[[main]]
  name = "Notes ğŸ“"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "note"
  weight = 10

[[main]]
  name = "Likes â¤ï¸"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "like"
  weight = 20

[[main]]
  name = "Music ğŸµ"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "music"
  weight = 30

[[main]]
  name = "Photos ğŸ“¸"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "photo"
  weight = 40

[[main]]
  name = "Bookmarks ğŸ”–"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "bookmark"
  weight = 50

[[main]]
  name = "Quotes ğŸ—£ï¸"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "quote"
  weight = 60

[[main]]
  name = "RePosts ğŸ”"
  parent = "Categories ğŸ—ƒï¸"
  pageRef= "repost"
  weight = 70

[[main]]
  name = "Videos ğŸ“½ï¸"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "video"
  weight = 80

[[main]]
  name = "Listen ğŸ™ï¸"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "listen"
  weight = 90

[[main]]
  name = "Reads ğŸ“š"
  parent = "Categories ğŸ—ƒï¸"
  pageRef = "read"
  weight = 100

#[[main]]
#  name = "Checkins ğŸ“"
#  parent = "Stream âš¡"
#  pageRef = "checkin"
#  weight = 40

#[[main]]
#  name = "Recommended â­"
#  pageRef = "#"
#  weight = 20



[[main]]
  name = "Kambo ğŸ¸"
  url = "https://kam.bo"
  weight = 30

[[main]]
  name = "About ğŸ§”ğŸ»â€â™‚ï¸"
  url = "/about"
  weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags ğŸ·ï¸"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories ğŸ—ƒï¸"
   pageRef = "category"
   weight = 20

